# https://hub.docker.com/_/mongo/
# https://github.com/docker-library/mongo/blob/master/4.1/Dockerfile
FROM mongo:4.4

ENV MONGO_INITDB_ROOT_USERNAME=root \
    MONGO_INITDB_ROOT_PASSWORD=1234 \
    MONGO_INITDB_DATABASE=default

EXPOSE 27017
