# https://docs.traefik.io
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  http:
    address: :80

# https://docs.traefik.io/providers/docker/
providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    useBindPortIP: false
    swarmMode: false
    swarmModeRefreshSeconds: '10s'
