# https://github.com/openzipkin/zipkin
# https://hub.docker.com/r/openzipkin/zipkin
# https://github.com/openzipkin/docker-zipkin
FROM openzipkin/zipkin

ENV STORAGE_TYPE=elasticsearch
ENV ES_HOSTS=http://elasticsearch:9200

EXPOSE 9411