# https://hub.docker.com/_/mysql/
# https://github.com/docker-library/mysql/blob/master/5.7/Dockerfile
FROM mysql:5.7

ENV MYSQL_ALLOW_EMPTY_PASSWORD=no
ENV MYSQL_ROOT_PASSWORD=1234
ENV MYSQL_DATABASE=zipkin
ENV MYSQL_USER=zipkin
ENV MYSQL_PASSWORD=zipkin

EXPOSE 3306