# https://hub.docker.com/_/openjdk
FROM openjdk:11.0.6

# https://docs.docker.com/engine/reference/builder/#label
LABEL MAINTAINER="lnhcode@outlook.com"
LABEL DOCKERFILE="https://github.com/linianhui/docker/tree/master/image/openjdk/11.0.6"

COPY sources.list /etc/apt/sources.list
