# https://github.com/linianhui/docker/pkgs/container/node
FROM ghcr.io/linianhui/node:16.13

# https://www.npmjs.com/package/sass
ENV SASS_VERSION=1.49.0

RUN npm install --global sass@${SASS_VERSION}
