version: '3'

services:

  # https://github.com/openzipkin/zipkin
  # https://hub.docker.com/r/openzipkin/zipkin
  # https://github.com/openzipkin/docker-zipkin
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://localhost:9200