# https://github.com/portainer/portainer
# https://hub.docker.com/r/portainer/portainer
FROM portainer/portainer

EXPOSE 9000

# https://portainer.readthedocs.io/en/stable/configuration.html 
ENTRYPOINT [ "/portainer","--no-auth" ]