# https://hub.docker.com/_/openjdk
FROM openjdk:8u232

# https://docs.docker.com/engine/reference/builder/#label
LABEL DOCKERFILE="https://github.com/linianhui/docker/tree/main/image/openjdk/8u232"

COPY sources.list /etc/apt/sources.list
