# https://hub.docker.com/r/gitlab/gitlab-ce
# https://hub.docker.com/r/gitlab/gitlab-runner-helper
# https://docs.gitlab.com/omnibus/docker
# https://hub.docker.com/r/gitlab/gitlab-ce/~/dockerfile

FROM gitlab/gitlab-ce

# https://docs.gitlab.com/ce/administration/environment_variables.html
# https://docs.gitlab.com/runner/install/linux-manually.html
# https://docs.gitlab.com/runner/register/index.html

EXPOSE 22 80 443
