version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  admin.mongo.test:
    build: ./image/admin.mongo/
    hostname: admin.mongo.test
    container_name: app-mongo-admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin-mongo.rule=Host(`admin.mongo.test`)
      - traefik.http.routers.admin-mongo.entrypoints=http
      - traefik.http.services.admin-mongo.loadbalancer.server.port=8081
