version: '3'

services:

  portainer:
    build: ./portainer/
    restart: always
    ports:
      - "80:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  zipkin:
    build: ./zipkin/
    restart: on-failure
    ports:
      - "9411:9411"

volumes:
  portainer_data: