version: '3'

services:

  zipkin:
    build: ./zipkin/
    networks:
      - network_default
    ports:
      - "9410:9410"
      - "9411:9411"

  elasticsearch:
    build: ./elasticsearch/
    networks:
      - network_default
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    networks:
      - network_default
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  mysql:
    build: ./mysql/
    networks:
      - network_default
    ports:
      - "3306:3306"
    volumes:
      - volume_mysql:/var/lib/mysql

  adminer:
    build: ./adminer/
    networks:
      - network_default
    ports:
      - "8080:8080"

networks:
  network_default:
    driver: bridge

volumes: 
  volume_mysql: 