version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  docker-api.test:
    build: ./image/docker-api/
    restart: always
    ports:
      - '2375:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
