version: '3'

services:

  socat:
    build: ./socat/
    restart: always
    networks:
      - network_default
    ports:
      - "2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer:
    build: ./portainer/
    restart: on-failure
    command: -H unix:///var/run/docker.sock
    networks:
      - network_default
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume_portainer:/data

networks:
  network_default:
    driver: bridge

volumes:
  volume_portainer:
