version: '3'

networks:
  network_default:
    driver: bridge

services:
  docker-api.test:
    build: ./image/docker-api/
    restart: always
    networks:
      - network_default
    ports:
      - '2375:2375'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
