version: '3'

services:

  mongo:
    build: ./mongo/
    networks:
      - network_default
    ports:
      - "27017:27017"
    volumes:
      - volume_mongo:/data/db

  rabbitmq:
    build: ./rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network_default
    volumes:
      - volume_rabbitmq:/var/lib/rabbitmq

  rebrow:
    build: ./rebrow/
    networks:
      - network_default
    ports:
      - "5001:5001"

  mongo-express:
    build: ./mongo-express/
    networks:
      - network_default
    ports:
      - "8081:8081"
networks:
  network_default:
    driver: bridge

volumes: 
  volume_mongo:
  volume_rabbitmq: