version: '3'

services:

  zipkin:
    build: ./zipkin/
    networks:
      - app_network
    ports:
      - "9410:9410"
      - "9411:9411"

  elasticsearch:
    build: ./elasticsearch/
    networks:
      - app_network
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    networks:
      - app_network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  app_network:
    driver: bridge
