version: '3'

services:

  portainer:
    build: ./portainer/
    restart: always
    networks:
      - app_network
    ports:
      - "80:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  zipkin:
    build: ./zipkin/
    restart: on-failure
    networks:
      - app_network
    ports:
      - "9410:9410"
      - "9411:9411"

  elasticsearch:
    build: ./elasticsearch/
    restart: on-failure
    networks:
      - app_network
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build: ./kibana/
    networks:
      - app_network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  portainer_data:

networks:
  app_network:
    driver: bridge