version: '3'

networks:
  network_default:
    driver: bridge

services:
  drone.test:
    build: ./image/drone/
    networks:
      - network_default
    volumes:
      - volume_drone:/var/lib/drone/
    labels:
      - traefik.enable=true
      - traefik.http.routers.drone.rule=Host(`drone.test`)
      - traefik.http.routers.drone.entrypoints=http
      - traefik.http.services.drone.loadbalancer.server.port=80

volumes:
  volume_drone:
