version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  drone.test:
    build: ./image/drone/
    volumes:
      - volume_drone:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.drone.rule=Host(`drone.test`)
      - traefik.http.routers.drone.entrypoints=http
      - traefik.http.services.drone.loadbalancer.server.port=80

volumes:
  volume_drone:
