version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  drone-agent:
    build: ./image/drone-agent/
    command: agent
    networks:
      - network_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
