version: '3'


networks:
  network_default:
    driver: bridge


services:

  drone-agent:
    build: ./images/drone-agent/
    command: agent
    networks:
      - network_default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock