version: '3'

networks:
  network_default:
    driver: bridge

services:
  echo:
    build: ./image/echo/
    networks:
      - network_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.echo.rule=Host(`echo.test`)
      - traefik.http.routers.echo.entrypoints=http
      - traefik.http.services.echo.loadbalancer.server.port=80
