version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  elasticsearch:
    build: ./image/elasticsearch/
    networks:
      - network_default
    ports:
      - '9200:9200'
      - '9300:9300'
