version: '3'

networks:
  network_default:
    driver: bridge

services:
  elasticsearch:
    build: ./image/elasticsearch/
    networks:
      - network_default
    ports:
      - '9200:9200'
      - '9300:9300'
