version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  gitea.test:
    build: ./image/gitea/
    restart: always
    volumes:
      - volume_gitea:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.test`)
      - traefik.http.routers.gitea.entrypoints=http
      - traefik.http.services.gitea.loadbalancer.server.port=80

volumes:
  volume_gitea:
