version: '3'

services:

  gitea:
    build: ./gitea/
    networks:
      - network_default
    volumes:
      - volume_gitea:/data
    labels:
      - traefik.enable=true
      - traefik.port=3000

networks:
  network_default:
    driver: bridge

volumes: 
  volume_gitea: