version: '3'

networks:
  network_default:
    driver: bridge

services:
  gitea:
    build: ./images/gitea/
    restart: always
    networks:
      - network_default
    ports:
      - '3000:3000'
    volumes:
      - volume_gitea:/data

volumes:
  volume_gitea:
