version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  gitea.lan:
    image: ghcr.io/linianhui/gitea:1.16
    hostname: gitea.lan
    container_name: app-gitea
    restart: always
    volumes:
      - volume_gitea:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.lan`)
      - traefik.http.routers.gitea.entrypoints=http
      - traefik.http.services.gitea.loadbalancer.server.port=80

volumes:
  volume_gitea:
