version: '3'

networks:
  network_default:
    driver: bridge

services:
  gitea.test:
    build: ./image/gitea/
    networks:
      - network_default
    volumes:
      - volume_gitea:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host(`gitea.test`)
      - traefik.http.routers.gitea.entrypoints=http
      - traefik.http.services.gitea.loadbalancer.server.port=3000

volumes:
  volume_gitea:
