version: '3'


networks:
  network_default:
    driver: bridge


services:

  gitlab-runner: # ./entrypoint register
    build: ./images/gitlab-runner/
    restart: always
    networks:
      - network_default
    volumes:
      - volume_gitlab-runner-home:/home/gitlab-runner
      - volume_gitlab-runner-etc:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock


volumes: 
  volume_gitlab-runner-home:
  volume_gitlab-runner-etc: