version: '3'


networks:
  network_default:
    driver: bridge


services:

  gitlab:
    build: ./gitlab/
    networks:
      - network_default
    ports:
      - "10080:10080"
    environment:
      # https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab:10080'
    volumes:
      - volume_gitlab-config:/etc/gitlab
      - volume_gitlab-log:/var/log/gitlab
      - volume_gitlab-data:/var/opt/gitlab


volumes: 
  volume_gitlab-config:
  volume_gitlab-log:
  volume_gitlab-data: