version: '3.9'

networks:
  default:
    external: true
    name: traefik-network


services:

  gitlab-ce:
    build: ./image/gitlab-ce/
    networks:
      - network_default
    ports:
      - "10080:10080"
    environment:
      # https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab-ce:10080'
    volumes:
      - volume_gitlab-ce-etc:/etc/gitlab
      - volume_gitlab-ce-log:/var/log/gitlab
      - volume_gitlab-ce-data:/var/opt/gitlab


volumes:
  volume_gitlab-ce-etc:
  volume_gitlab-ce-log:
  volume_gitlab-ce-data:
