version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  echo.test:
    image: ghcr.io/linianhui/http-echo
    labels:
      - traefik.enable=true
      - traefik.http.routers.echo.rule=Host(`echo.test`)
      - traefik.http.routers.echo.entrypoints=http
      - traefik.http.services.echo.loadbalancer.server.port=80
