version: '3'

networks:
  network_default:
    driver: bridge

services:
  jenkins.test:
    build: ./image/jenkins/
    networks:
      - network_default
    volumes:
      - volume_jenkins:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.test`)
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

volumes:
  volume_jenkins:
