version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  jenkins.test:
    image: ghcr.io/linianhui/jenkins:2.332
    hostname: jenkins.test
    container_name: app-jenkins
    volumes:
      - volume_jenkins:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.test`)
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

volumes:
  volume_jenkins:
