version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  jenkins.test:
    build: ./image/jenkins/
    volumes:
      - volume_jenkins:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.test`)
      - traefik.http.routers.jenkins.entrypoints=http
      - traefik.http.services.jenkins.loadbalancer.server.port=8080

volumes:
  volume_jenkins:
