version: '3'

services:

  jenkins:
    build: ./jenkins/
    networks:
      - network_default
    volumes:
      - volume_jenkins:/var/jenkins_home
    labels:
      - traefik.enable=true
      - traefik.port=8080

networks:
  network_default:
    driver: bridge

volumes: 
  volume_jenkins: