version: '3'

services:

  mongo:
    build: ./mongo/
    networks:
      - network_default
    ports:
      - "27017:27017"
    volumes:
      - volume_mongo:/data/db

networks:
  network_default:
    driver: bridge

volumes: 
  volume_mongo: