version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  mongo.test:
    build: ./image/mongo/
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - volume_mongo-db:/data/db
      - volume_mongo-configdb:/data/configdb

volumes:
  volume_mongo-db:
  volume_mongo-configdb:
