version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  admin.mongo.lan:
    image: ghcr.io/linianhui/mongo-admin:0.54
    hostname: admin.mongo.lan
    container_name: app-mongo-admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin-mongo.rule=Host(`admin.mongo.lan`)
      - traefik.http.routers.admin-mongo.entrypoints=http
      - traefik.http.services.admin-mongo.loadbalancer.server.port=8081
