version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  mongo.lan:
    image: ghcr.io/linianhui/mongo:5.0
    hostname: mongo.lan
    container_name: app-mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=default
    volumes:
      - volume_mongo-db:/data/db
      - volume_mongo-configdb:/data/configdb

volumes:
  volume_mongo-db:
  volume_mongo-configdb:
