version: '3'

services:
  mysql-admin:
    build: ./image/mysql-admin/
    networks:
      - network_default
    ports:
      - '13306:80'
    volumes:
      - volume_mysql-admin:/sessions

networks:
  network_default:
    driver: bridge

volumes:
  volume_mysql-admin:
