version: '3'

services:

  mysql-admin:
    build: ./mysql-admin/
    networks:
      - network_default
    ports:
      - "13306:8080"
    volumes:
      - volume_mysql-admin:/tmp

networks:
  network_default:
    driver: bridge

volumes:
  volume_mysql-admin:
