version: '3'

services:
  mysql:
    build: ./images/mysql/
    networks:
      - network_default
    ports:
      - '3306:3306'
    volumes:
      - volume_mysql:/var/lib/mysql

networks:
  network_default:
    driver: bridge

volumes:
  volume_mysql:
