version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  admin.mysql.test:
    image: ghcr.io/linianhui/mysql-admin:5.1
    hostname: admin.mysql.test
    container_name: app-mysql-admin
    restart: always
    volumes:
      - volume_admin-mysql:/sessions
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin-mysql.rule=Host(`admin.mysql.test`)
      - traefik.http.routers.admin-mysql.entrypoints=http
      - traefik.http.services.admin-mysql.loadbalancer.server.port=80

volumes:
  volume_admin-mysql:
