version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  mysql.test:
    build: ./image/mysql/
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - volume_mysql:/var/lib/mysql

volumes:
  volume_mysql:
