version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  admin.mysql.test:
    image: ghcr.io/linianhui/mysql-admin:5.1
    restart: always
    environment:
      - PMA_HOST=mysql.test
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=1234
      - PMA_ARBITRARY=1
    volumes:
      - volume_admin-mysql:/sessions
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin-mysql.rule=Host(`admin.mysql.test`)
      - traefik.http.routers.admin-mysql.entrypoints=http
      - traefik.http.services.admin-mysql.loadbalancer.server.port=80

volumes:
  volume_admin-mysql:
