version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  mysql-admin.test:
    build: ./image/mysql-admin/
    volumes:
      - volume_mysql-admin:/sessions
    labels:
      - traefik.enable=true
      - traefik.http.routers.mysql-admin.rule=Host(`mysql-admin.test`)
      - traefik.http.routers.mysql-admin.entrypoints=http
      - traefik.http.services.mysql-admin.loadbalancer.server.port=80

volumes:
  volume_mysql-admin:
