version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  mysql.test:
    image: ghcr.io/linianhui/mysql:8.0
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test
    ports:
      - '3306:3306'
    volumes:
      - volume_mysql:/var/lib/mysql

volumes:
  volume_mysql:
