version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  openwrt.lan:
    image: ghcr.io/linianhui/openwrt:x86-64-22.03.2
    hostname: openwrt.lan
    container_name: app-openwrt
    labels:
      - traefik.enable=true
      - traefik.http.routers.openwrt.rule=Host(`openwrt.lan`)
      - traefik.http.routers.openwrt.entrypoints=http
      - traefik.http.services.openwrt.loadbalancer.server.port=80
