version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  portainer.test:
    build: ./image/portainer/
    restart: on-failure
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume_portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.test`)
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.services.portainer.loadbalancer.server.port=9000

volumes:
  volume_portainer:
