version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  portainer.lan:
    image: ghcr.io/linianhui/portainer-ce:2.15.1
    hostname: portainer.lan
    container_name: app-portainer
    restart: on-failure
    command: --host unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - volume_portainer:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.lan`)
      - traefik.http.routers.portainer.entrypoints=http
      - traefik.http.services.portainer.loadbalancer.server.port=80

volumes:
  volume_portainer:
