version: '3'


networks:
  network_default:
    driver: bridge


services:

  rabbitmq:
    build: ./images/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - network_default
    volumes:
      - volume_rabbitmq:/var/lib/rabbitmq


volumes: 
  volume_rabbitmq: