version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  rabbitmq:
    build: ./image/rabbitmq/
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - network_default
    volumes:
      - volume_rabbitmq:/var/lib/rabbitmq

volumes:
  volume_rabbitmq:
