version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  redis.lan:
    image: ghcr.io/linianhui/redis:6.2
    hostname: redis.lan
    container_name: app-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - volume_redis:/data

volumes:
  volume_redis:
