version: '3'


networks:
  network_default:
    driver: bridge


services:

  redis:
    build: ./redis/
    networks:
      - network_default
    ports:
      - "6379:6379"
    volumes:
      - volume_redis:/data


volumes: 
  volume_redis: