version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  admin.redis.test:
    image: ghcr.io/linianhui/redis-admin
    hostname: admin.redis.test
    container_name: app-redis-admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.admin-redis.rule=Host(`admin.redis.test`)
      - traefik.http.routers.admin-redis.entrypoints=http
      - traefik.http.services.admin-redis.loadbalancer.server.port=5001
