version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  redis.test:
    build: ./image/redis/
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - volume_redis:/data

volumes:
  volume_redis:
