version: '3'

networks:
  network_default:
    driver: bridge

services:
  registry.test:
    build: ./image/registry/
    networks:
      - network_default
    volumes:
      - volume_registry:/var/lib/registry
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.test`)
      - traefik.http.routers.registry.entrypoints=http
      - traefik.http.services.registry.loadbalancer.server.port=5000

volumes:
  volume_registry:
