version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  registry.test:
    build: ./image/registry/
    restart: always
    volumes:
      - volume_registry:/var/lib/registry
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.rule=Host(`registry.test`)
      - traefik.http.routers.registry.entrypoints=http
      - traefik.http.services.registry.loadbalancer.server.port=80

volumes:
  volume_registry:
