version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  traefik.lan:
    image: ghcr.io/linianhui/traefik:v2.10
    hostname: traefik.lan
    container_name: app-traefik
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # https://docs.traefik.io/routing/providers/docker/
    # https://docs.traefik.io/reference/dynamic-configuration/docker/
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.lan`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
