version: '3'

networks:
  default:
    external:
      name: traefik-network

services:
  traefik.test:
    image: ghcr.io/linianhui/traefik:2.4
    restart: always
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # https://docs.traefik.io/routing/providers/docker/
    # https://docs.traefik.io/reference/dynamic-configuration/docker/
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.test`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
