version: '3'

networks:
  network_default:
    driver: bridge

services:
  traefik:
    build: ./image/traefik/
    restart: always
    networks:
      - network_default
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # https://docs.traefik.io/routing/providers/docker/#configuration-examples
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.test`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080