version: '3.9'

networks:
  default:
    external: true
    name: traefik-network

services:
  zipkin.test:
    build: ./image/zipkin/
    labels:
      - traefik.enable=true
      - traefik.http.routers.zipkin.rule=Host(`zipkin.test`)
      - traefik.http.routers.zipkin.entrypoints=http
      - traefik.http.services.zipkin.loadbalancer.server.port=9411
