version: '3'

networks:
  network_default:
    driver: bridge

services:
  zipkin:
    build: ./image/zipkin/
    networks:
      - network_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.zipkin.rule=Host(`zipkin.test`)
      - traefik.http.services.zipkin.loadbalancer.server.port=9411
