# https://github.com/netdata/netdata
# https://hub.docker.com/r/netdata/netdata
FROM netdata/netdata

# https://docs.docker.com/engine/reference/builder/#label
LABEL DOCKERFILE="https://github.com/linianhui/docker/tree/main/image/netdata/latest"

ENV NETDATA_PORT=80

EXPOSE 80
