# https://github.com/netdata/netdata
# https://hub.docker.com/r/netdata/netdata
FROM netdata/netdata

# https://docs.docker.com/engine/reference/builder/#label
LABEL MAINTAINER="lnhcode@outlook.com"
LABEL DOCKERFILE="https://github.com/linianhui/docker/tree/master/image/netdata/latest"

ENV NETDATA_PORT=80

EXPOSE 80