# https://hub.docker.com/r/drone/agent
# http://docs.drone.io/installation

FROM drone/agent

# http://docs.drone.io/installation/
ENV DRONE_RPC_HOST=drone.test \
    DRONE_RPC_PROTO=9000 \
    DRONE_RPC_SECRET=1234
