# https://hub.docker.com/r/gitlab/gitlab-ce
# https://docs.gitlab.com/omnibus/docker
# https://hub.docker.com/r/gitlab/gitlab-ce/~/dockerfile

FROM gitlab/gitlab-ce

# https://docs.gitlab.com/ce/administration/environment_variables.html

EXPOSE 22 80 443
