# https://github.com/openzipkin/zipkin
# https://hub.docker.com/r/openzipkin/zipkin
# https://github.com/openzipkin/docker-zipkin
FROM openzipkin/zipkin:2.23

# https://github.com/openzipkin/zipkin/tree/master/zipkin-server#mysql-storage
# https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/mysql-v1/src/main/resources/mysql.sql

# ENV STORAGE_TYPE=mysql \
#    MYSQL_HOST=mysql \
#    MYSQL_DB=zipkin \
#    MYSQL_USER=zipkin \
#    MYSQL_PASS=zipkin

EXPOSE 9410 9411
