# https://hub.docker.com/r/gitea/gitea
# https://github.com/go-gitea/gitea/blob/master/Dockerfile
# https://docs.gitea.io/zh-cn/
FROM lnhcode/gitea:1.10.1

# https://github.com/go-gitea/gitea/blob/master/docker/root/etc/s6/gitea/setup
# https://github.com/go-gitea/gitea/blob/master/docker/root/etc/templates/app.ini
# https://github.com/go-gitea/gitea/blob/master/custom/conf/app.ini.sample
ENV ROOT_URL=http://gitea.test

EXPOSE 22 80
