# https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
# kubectl apply -f echo.replica-set.yml echo-replica-set
# kubectl get rs -o wide
# kubectl describe rs echo-replica-set
# kubectl delete -f echo.replica-set.yml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo-replica-set
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      name: echo
      labels:
        app: echo
    spec:
      containers:
        - name: echo-replica-set-container
          image: lnhcode/echo
          ports:
            - containerPort: 80
      restartPolicy: Always
