# https://hub.docker.com/r/gitlab/gitlab-runner
# https://hub.docker.com/r/gitlab/gitlab-runner/~/dockerfile/
FROM gitlab/gitlab-runner:alpine

# https://docs.gitlab.com/runner/install/docker.html
# https://docs.gitlab.com/runner/install/linux-manually.html
# https://docs.gitlab.com/runner/register/index.html

# https://docs.gitlab.com/runner/register/index.html#docker
