name: ci

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ contains(github.event.head_commit.message,'--ci') }}

    steps:
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: login to gitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: analyze the imgae meta to be pushed
        env:
           GIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: ./ci.sh init ${GIT_MESSAGE#*--ci}

      - name: docker build
        run: ./ci.sh build

      - name: docker push
        run: ./ci.sh push
